### PR TITLE
Troubleshooting quickstart by adding missing packages and providing a fix for sqlite3 version

### PR DESCRIPTION
**Pull request by TiphaineLAURENT**
Hi again,

On https://github.com/charlesdedampierre/BunkaTopics/pull/24 you suggested I test the new architecture, so I did.
I found small improvements I hope will help.

I am also wondering why you dropped poetry ?

Tiphaine LAURENT
on behalf of Alivia

### CODE REVIEW

**Comment by charlesdedampierre** [comment]
well found for the README.md mistake :)

In the new version, there is no more need for sqlite3 now so I suggest you remove it and only keep the README, or is it something I did not understand ?

Regarding poetry, I found the configuration for extras dependencies like "pip install '.[test]'" complex, so I dropped it, python venv is great as well.

**Comment by TiphaineLAURENT** [comment]
Thanks,

sqlite3 is a dependency of chromadb but the version embedded in Python depends on Python (see the commit message for more explanation including a link to chromadb troubleshooting).

Fine with me for poetry. I'm also using venv

**Comment by charlesdedampierre** [comment]
What would be helpful is to separate the 2 problems (Readme) and chroma into 2 PR. Maybe you can make a quick one for the READE that I can accept right away and we keep this one for the chroma discussion.

Thanks!

**Comment by TiphaineLAURENT** [comment]
Sorry for the delay, it seems we are on different timezones.

I'll move the README/pywidget to another PR

**Comment by TiphaineLAURENT** [comment]
I moved the commits to https://github.com/charlesdedampierre/BunkaTopics/pull/43

**Pull request closed without merging**
